#!/usr/bin/env node
// Build index.html from deck.json.
//
// Each slide is a clip whose composition lives in compositions/<id>.html.
// Timing model (all seconds):
//   rests    — local times where the presenter parks on "next". One rest = a plain
//              slide; several = click-by-click builds (HyperFrames "fragments").
//   start    — the next slide starts 0.05s after the previous slide's last rest,
//              so pressing "next" immediately plays its wipe-in over the old slide.
//   duration — lastRest + 0.6, so a slide stays visible under the incoming wipe.
// Slides alternate tracks 0/1 because consecutive clips overlap during the wipe.
//
// Usage: node scripts/build-deck.mjs     (from the project folder)

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const deck = JSON.parse(readFileSync('deck.json', 'utf8'));
const TAIL = 0.6;
const GAP = 0.05;
const r3 = (n) => Math.round(n * 1000) / 1000;
const FPS = 30;
// Park a fifth of a frame PAST the boundary: the player floors seek times to
// whole frames, and a stop authored exactly on a boundary can round to just
// below it and land one frame early. This lands on the intended frame either way.
const frame = (n) => Math.round(((Math.round(n * FPS) + 0.2) / FPS) * 10000) / 10000;

let t = 0;
const clips = [];
const island = { slides: [] };
const problems = [];

deck.slides.forEach((s, i) => {
  const src = `compositions/${s.id}.html`;
  if (!existsSync(src)) problems.push(`missing ${src}`);
  const rests = [...s.rests].sort((a, b) => a - b);
  const last = rests[rests.length - 1];
  const dur = r3(last + TAIL);
  const start = r3(t);

  if (existsSync(src)) {
    const m = readFileSync(src, 'utf8').match(/data-composition-id="([^"]+)"[^>]*data-duration="([0-9.]+)"/);
    if (!m || m[1] !== s.id) problems.push(`${src}: data-composition-id should be "${s.id}"`);
    else if (Math.abs(parseFloat(m[2]) - dur) > 0.001) problems.push(`${src}: data-duration is ${m[2]}, deck.json implies ${dur} (lastRest + ${TAIL})`);
  }

  clips.push(`      <div id="${s.id}" class="slide-layer" data-composition-id="${s.id}"
        data-composition-src="${src}"
        data-start="${start}" data-duration="${dur}" data-track-index="${i % 2}"
        data-width="1920" data-height="1080"></div>`);

  // Clips overlap during the wipe, but presenter ranges must not: each slide's
  // range ends exactly where the next slide's clip begins.
  const isLast = i === deck.slides.length - 1;
  island.slides.push({
    sceneId: s.id,
    startTime: start,
    endTime: isLast ? r3(start + dur) : r3(start + last + GAP),
    fragments: rests.map((r) => frame(start + r)),
    notes: s.notes || ''
  });
  t = start + last + GAP;
});

const total = r3(t - GAP + TAIL);

if (problems.length) {
  console.error('deck.json problems:\n  ' + problems.join('\n  '));
  process.exit(1);
}

const bridge = readFileSync('scripts/motion-bridge.js', 'utf8');

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>${deck.title.replace(/</g, '&lt;')}</title>
    <!-- GENERATED by scripts/build-deck.mjs from deck.json. Edit deck.json, then rebuild. -->
    <script src="assets/gsap.min.js"></script>
    <!-- Fonts are self-hosted in assets/fonts (declared in deck.css). Preloading
         them means the first slide never plays while text is still invisible,
         and the deck presents fully offline. -->
    <link rel="preload" href="assets/fonts/Sora.woff2" as="font" type="font/woff2" crossorigin />
    <link rel="preload" href="assets/fonts/Manrope.woff2" as="font" type="font/woff2" crossorigin />
    <link rel="preload" href="assets/fonts/JetBrainsMono.woff2" as="font" type="font/woff2" crossorigin />
    <link rel="stylesheet" href="assets/deck.css" />
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { width: 1920px; height: 1080px; overflow: hidden; background: #F1ECE3; }
      .slide-layer { position: absolute; top: 0; left: 0; width: 1920px; height: 1080px; }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="digiwell-deck"
      data-start="0" data-duration="${total}" data-width="1920" data-height="1080">
${clips.join('\n\n')}
    </div>

    <!-- Presenter manifest for \`npx hyperframes present\`: one entry per slide,
         fragments = the global times the presenter parks on. -->
    <script type="application/hyperframes-slideshow+json">
${JSON.stringify(island, null, 2)}
    </script>

    <script>
      window.__timelines = window.__timelines || {};
      const tl = gsap.timeline({ paused: true });
      tl.to({}, { duration: ${total} }, 0);
      window.__timelines["digiwell-deck"] = tl;
    </script>
${deck.motionBridge ? `
    <script>
${bridge}
    </script>` : ''}
  </body>
</html>
`;

writeFileSync('index.html', html);
console.log(`index.html: ${deck.slides.length} slides, ${island.slides.reduce((n, s) => n + s.fragments.length, 0)} stops, ${total}s timeline`);
